1 develop auto testing suit for monorepo
eclipse-volttron/volttron-boptest pull request #11
Opened 2023-08-01 23:47 UTC by kefeimo

Resolve Issue #1 

* Created pytest suits for both sub-mono-repos.
* Pre-run workflows result
    * [1 develop auto testing suit for monorepo](https://github.com/kefeimo/volttron-boptest/actions/runs/5732902646)
    * [1 develop auto testing suit for monorepo](https://github.com/kefeimo/volttron-boptest/actions/runs/5732902637)

2023-08-15 00:38 UTC, craigpnnl requested changes

2023-08-15 00:38 UTC, craigpnnl commented on .github/workflows/run-volttron-boptest-agent-tests.yml
> +#      - name: validate repo
please remove the commented out code unless there for documentation of purpose.

2023-08-15 00:38 UTC, craigpnnl commented on .github/workflows/run-volttron-lib-boptest-integration-tests.yml
> +#      - name: install docker-compose
remove commented out code that aren't relevent

2023-08-15 00:46 UTC, craig8 requested changes

2023-08-15 00:46 UTC, craigpnnl commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +@pytest.fixture(scope="module")
I don't understand why you are doing this.

The volttron instance creates a new volttron_home for every test instance.  Why are we testing this here?

2023-08-15 00:46 UTC, craig8 commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +def vip_agent(volttron_instance):
These tests are already done in the volttron-testing library

2023-08-15 00:46 UTC, craig8 commented on volttron-lib-boptest-integration/tests/conftest.py
> +"""Configuration for the pytest test suits (make sure /src is resolvable)."""
should be suite not suit

2023-08-15 00:46 UTC, craigpnnl commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +    puid = boptest_agent
this isn't necessary...you can use the dynamic_agent that is started for each instance to do peerlist on.

2023-08-15 01:31 UTC, kefeimo commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +@pytest.fixture(scope="module")
This is mainly for debugging purpose, i.e., to display what volttron home is. The intention is to make sure each test unit is working and help to narrow down the root cause. 
Should I
* skip the test
* comment out the test
* or, delete the code block?

2023-08-15 01:31 UTC, kefeimo commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +def vip_agent(volttron_instance):
The intention is to make sure each test unit is working and help to narrow down the root cause. 
Should I
* skip the test
* comment out the test
* or, delete the code block?

2023-08-15 01:31 UTC, kefeimo commented on volttron-lib-boptest-integration/tests/conftest.py
> +"""Configuration for the pytest test suits (make sure /src is resolvable)."""
resolved

2023-08-15 01:31 UTC, kefeimo commented on volttron-boptest-agent/tests/test_boptest_agent.py
> +    puid = boptest_agent
I am following the pattern of volttron-lib-fake-driver: https://github.com/eclipse-volttron/volttron-lib-fake-driver/blob/main/tests/test_driver.py#L90.

Is there an example of using dynamic_agent? Does it have Python api or we will utilize subprocess to call from command line?

2023-08-15 01:31 UTC, kefeimo commented on .github/workflows/run-volttron-boptest-agent-tests.yml
> +#      - name: validate repo
resolved

2023-08-15 01:31 UTC, kefeimo commented on .github/workflows/run-volttron-lib-boptest-integration-tests.yml
> +#      - name: install docker-compose
resolved

2023-08-15 01:33 UTC, kefeimo reviewed
changed based @craig8 's feedback

2023-08-15 17:12 UTC, kefeimo commented
@craig8, thanks for the review. I responded inline. (Somehow github doesn't give me the option to re-request review.)

2023-09-06 22:11 UTC, craig8 approved these changes

2023-09-26 17:42 UTC, shwethanidd approved these changes

2023-09-26 17:43 UTC, merged